### ISSUE TITLE
Смена версии Node.js

### ISSUE THREAD

**Issue by korab1ev** [citec-spbu/Urban-Topology#32]

**Comment by vlad-stepanov** [comment]
Проект не поднимался из-за ошибки, связанной с неправильной версией Node.js, обновление версии в соответствующем `Dockerfile` помогло решить проблему.

**Comment by korab1ev** [comment]
До этого в проекте использовалось
FROM node:16 и вызывало ошибку (если запустить с node:16 то в логах можно будет найти). 
Теперь используется версия 18, которая решила проблему.
