### ISSUE TITLE
Построить визуализацию метрик Degree Centrality, Closeness centrality, Betweenness Centrality на произвольно сгенерированном графе

### ISSUE THREAD

**Issue by korab1ev** [citec-spbu/Urban-Topology#9]
Визуализация для каждой метрики должна выглядеть примерно так (на странице https://www.networkpages.nl/centrality-measures-who-is-the-most-important-in-a-network/ можно потыкать разные метрики и  посмотреть как будет меняться визуализация):

![example](https://github.com/user-attachments/assets/5d0df36d-6c36-488b-ae23-ae3e6ab53716)

**Comment by IlyaKuprik** [comment]
Добавил построение графов метрик на произвольном графе, пока что не стал встраивать в общий пайплайн, займусь, когда наш бекенд начнет возвращать графы и отрисовывать точки. https://github.com/citec-spbu/Urban-Topology/blob/graph-metrics/analytics/metrics.ipynb
